<?php
/**
 * BoletoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API BaaS - Atar B2B
 *
 * Documentação da API do serviço de Banking as a Service.
 *
 * OpenAPI spec version: v3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.30
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * BoletoTest Class Doc Comment
 *
 * @category    Class
 * @description Objeto de boleto
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BoletoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Boleto"
     */
    public function testBoleto()
    {
    }

    /**
     * Test attribute "cashin_id"
     */
    public function testPropertyCashinId()
    {
    }

    /**
     * Test attribute "transaction_id"
     */
    public function testPropertyTransactionId()
    {
    }

    /**
     * Test attribute "due_date"
     */
    public function testPropertyDueDate()
    {
    }

    /**
     * Test attribute "settle_date"
     */
    public function testPropertySettleDate()
    {
    }

    /**
     * Test attribute "timestamp"
     */
    public function testPropertyTimestamp()
    {
    }

    /**
     * Test attribute "typeful_line"
     */
    public function testPropertyTypefulLine()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "original_amount"
     */
    public function testPropertyOriginalAmount()
    {
    }

    /**
     * Test attribute "amount_paid"
     */
    public function testPropertyAmountPaid()
    {
    }

    /**
     * Test attribute "max_value"
     */
    public function testPropertyMaxValue()
    {
    }

    /**
     * Test attribute "min_value"
     */
    public function testPropertyMinValue()
    {
    }

    /**
     * Test attribute "discount"
     */
    public function testPropertyDiscount()
    {
    }

    /**
     * Test attribute "interest"
     */
    public function testPropertyInterest()
    {
    }

    /**
     * Test attribute "beneficiary"
     */
    public function testPropertyBeneficiary()
    {
    }

    /**
     * Test attribute "beneficiary_document"
     */
    public function testPropertyBeneficiaryDocument()
    {
    }

    /**
     * Test attribute "payer"
     */
    public function testPropertyPayer()
    {
    }

    /**
     * Test attribute "payer_document"
     */
    public function testPropertyPayerDocument()
    {
    }

    /**
     * Test attribute "assignor"
     */
    public function testPropertyAssignor()
    {
    }

    /**
     * Test attribute "can_change_amount"
     */
    public function testPropertyCanChangeAmount()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }
}
