<?php
/**
 * CashinOptionsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API BaaS - Atar B2B
 *
 * Documentação da API do serviço de Banking as a Service.
 *
 * OpenAPI spec version: v3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.30
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CashinOptionsTest Class Doc Comment
 *
 * @category    Class
 * @description Opcoes de cashin e seus limites
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CashinOptionsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CashinOptions"
     */
    public function testCashinOptions()
    {
    }

    /**
     * Test attribute "boleto"
     */
    public function testPropertyBoleto()
    {
    }

    /**
     * Test attribute "ted"
     */
    public function testPropertyTed()
    {
    }

    /**
     * Test attribute "credit_card"
     */
    public function testPropertyCreditCard()
    {
    }

    /**
     * Test attribute "boleto_limits"
     */
    public function testPropertyBoletoLimits()
    {
    }

    /**
     * Test attribute "wallet_limits"
     */
    public function testPropertyWalletLimits()
    {
    }

    /**
     * Test attribute "ted_items"
     */
    public function testPropertyTedItems()
    {
    }
}
