<?php
/**
 * PixRefundTypeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API BaaS - Atar B2B
 *
 * Documentação da API do serviço de Banking as a Service.
 *
 * OpenAPI spec version: v3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.30
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PixRefundTypeTest Class Doc Comment
 *
 * @category    Class
 * @description Tipos de devolução:  * &#x60;MD06&#x60; - RefundRequestByEndCustomer  * &#x60;AM05&#x60; - Duplication  * &#x60;AM09&#x60; - WrongAmount  * &#x60;BE08&#x60; - BankError  * &#x60;DS28&#x60; - ReturnForTechnicalReason  * &#x60;FOCR&#x60; - FollowingCancellationRequest  * &#x60;FR01&#x60; - Fraud  * &#x60;NARR&#x60; - Narrative  * &#x60;RUTA&#x60; - ReturnUponUnableToApply  * &#x60;SL11&#x60; - Creditor not on Whitelist of Debtor  * &#x60;SL12&#x60; - Creditor on Blacklist of Debtor  * &#x60;UPAY&#x60; - UnduePayment
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PixRefundTypeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PixRefundType"
     */
    public function testPixRefundType()
    {
    }
}
