<?php
/**
 * TransferOptionsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API BaaS - Atar B2B
 *
 * Documentação da API do serviço de Banking as a Service.
 *
 * OpenAPI spec version: v3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.30
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * TransferOptionsTest Class Doc Comment
 *
 * @category    Class
 * @description Opcoes de transferencia e seus limites
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TransferOptionsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TransferOptions"
     */
    public function testTransferOptions()
    {
    }

    /**
     * Test attribute "external_transfer_start_hour"
     */
    public function testPropertyExternalTransferStartHour()
    {
    }

    /**
     * Test attribute "external_transfer_end_hour"
     */
    public function testPropertyExternalTransferEndHour()
    {
    }

    /**
     * Test attribute "is_business_day"
     */
    public function testPropertyIsBusinessDay()
    {
    }

    /**
     * Test attribute "fee_external_transfer"
     */
    public function testPropertyFeeExternalTransfer()
    {
    }

    /**
     * Test attribute "banks"
     */
    public function testPropertyBanks()
    {
    }

    /**
     * Test attribute "account_types"
     */
    public function testPropertyAccountTypes()
    {
    }

    /**
     * Test attribute "limits"
     */
    public function testPropertyLimits()
    {
    }
}
