<?php
/**
 * UserMePutTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API BaaS - Atar B2B
 *
 * Documentação da API do serviço de Banking as a Service.
 *
 * OpenAPI spec version: v3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.30
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * UserMePutTest Class Doc Comment
 *
 * @category    Class
 * @description UserMePut
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UserMePutTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "UserMePut"
     */
    public function testUserMePut()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "phone"
     */
    public function testPropertyPhone()
    {
    }

    /**
     * Test attribute "fiscal_country"
     */
    public function testPropertyFiscalCountry()
    {
    }

    /**
     * Test attribute "nif"
     */
    public function testPropertyNif()
    {
    }

    /**
     * Test attribute "rg_number"
     */
    public function testPropertyRgNumber()
    {
    }

    /**
     * Test attribute "monthly_income"
     */
    public function testPropertyMonthlyIncome()
    {
    }

    /**
     * Test attribute "patrimony"
     */
    public function testPropertyPatrimony()
    {
    }

    /**
     * Test attribute "cbo_id"
     */
    public function testPropertyCboId()
    {
    }

    /**
     * Test attribute "addresses"
     */
    public function testPropertyAddresses()
    {
    }

    /**
     * Test attribute "has_accepted_residence_declaration"
     */
    public function testPropertyHasAcceptedResidenceDeclaration()
    {
    }

    /**
     * Test attribute "has_accepted_terms"
     */
    public function testPropertyHasAcceptedTerms()
    {
    }

    /**
     * Test attribute "has_accepted_privacy_policy"
     */
    public function testPropertyHasAcceptedPrivacyPolicy()
    {
    }

    /**
     * Test attribute "otp"
     */
    public function testPropertyOtp()
    {
    }
}
