<?php
/**
 * PixRefundType
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API BaaS - Atar B2B
 *
 * Documentação da API do serviço de Banking as a Service.
 *
 * OpenAPI spec version: v3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.30
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * PixRefundType Class Doc Comment
 *
 * @category Class
 * @description Tipos de devolução:  * &#x60;MD06&#x60; - RefundRequestByEndCustomer  * &#x60;AM05&#x60; - Duplication  * &#x60;AM09&#x60; - WrongAmount  * &#x60;BE08&#x60; - BankError  * &#x60;DS28&#x60; - ReturnForTechnicalReason  * &#x60;FOCR&#x60; - FollowingCancellationRequest  * &#x60;FR01&#x60; - Fraud  * &#x60;NARR&#x60; - Narrative  * &#x60;RUTA&#x60; - ReturnUponUnableToApply  * &#x60;SL11&#x60; - Creditor not on Whitelist of Debtor  * &#x60;SL12&#x60; - Creditor on Blacklist of Debtor  * &#x60;UPAY&#x60; - UnduePayment
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PixRefundType
{
    /**
     * Possible values of this enum
     */
    const MD06 = 'MD06';
const AM05 = 'AM05';
const AM09 = 'AM09';
const BE08 = 'BE08';
const DS28 = 'DS28';
const FOCR = 'FOCR';
const FR01 = 'FR01';
const NARR = 'NARR';
const RUTA = 'RUTA';
const SL11 = 'SL11';
const SL12 = 'SL12';
const UPAY = 'UPAY';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::MD06,
self::AM05,
self::AM09,
self::BE08,
self::DS28,
self::FOCR,
self::FR01,
self::NARR,
self::RUTA,
self::SL11,
self::SL12,
self::UPAY,        ];
    }
}
