<?php
/**
 * TransferOptions
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API BaaS - Atar B2B
 *
 * Documentação da API do serviço de Banking as a Service.
 *
 * OpenAPI spec version: v3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.30
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * TransferOptions Class Doc Comment
 *
 * @category Class
 * @description Opcoes de transferencia e seus limites
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TransferOptions implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'TransferOptions';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'external_transfer_start_hour' => 'string',
'external_transfer_end_hour' => 'string',
'is_business_day' => 'bool',
'fee_external_transfer' => 'int',
'banks' => '\Swagger\Client\Model\KeyValue[]',
'account_types' => '\Swagger\Client\Model\KeyValue[]',
'limits' => '\Swagger\Client\Model\CashinLimits'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'external_transfer_start_hour' => null,
'external_transfer_end_hour' => null,
'is_business_day' => null,
'fee_external_transfer' => 'int32',
'banks' => null,
'account_types' => null,
'limits' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'external_transfer_start_hour' => 'externalTransferStartHour',
'external_transfer_end_hour' => 'externalTransferEndHour',
'is_business_day' => 'isBusinessDay',
'fee_external_transfer' => 'feeExternalTransfer',
'banks' => 'banks',
'account_types' => 'accountTypes',
'limits' => 'limits'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'external_transfer_start_hour' => 'setExternalTransferStartHour',
'external_transfer_end_hour' => 'setExternalTransferEndHour',
'is_business_day' => 'setIsBusinessDay',
'fee_external_transfer' => 'setFeeExternalTransfer',
'banks' => 'setBanks',
'account_types' => 'setAccountTypes',
'limits' => 'setLimits'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'external_transfer_start_hour' => 'getExternalTransferStartHour',
'external_transfer_end_hour' => 'getExternalTransferEndHour',
'is_business_day' => 'getIsBusinessDay',
'fee_external_transfer' => 'getFeeExternalTransfer',
'banks' => 'getBanks',
'account_types' => 'getAccountTypes',
'limits' => 'getLimits'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['external_transfer_start_hour'] = isset($data['external_transfer_start_hour']) ? $data['external_transfer_start_hour'] : null;
        $this->container['external_transfer_end_hour'] = isset($data['external_transfer_end_hour']) ? $data['external_transfer_end_hour'] : null;
        $this->container['is_business_day'] = isset($data['is_business_day']) ? $data['is_business_day'] : null;
        $this->container['fee_external_transfer'] = isset($data['fee_external_transfer']) ? $data['fee_external_transfer'] : null;
        $this->container['banks'] = isset($data['banks']) ? $data['banks'] : null;
        $this->container['account_types'] = isset($data['account_types']) ? $data['account_types'] : null;
        $this->container['limits'] = isset($data['limits']) ? $data['limits'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets external_transfer_start_hour
     *
     * @return string
     */
    public function getExternalTransferStartHour()
    {
        return $this->container['external_transfer_start_hour'];
    }

    /**
     * Sets external_transfer_start_hour
     *
     * @param string $external_transfer_start_hour Timestamp da hora inicial da janela para transferencia externa
     *
     * @return $this
     */
    public function setExternalTransferStartHour($external_transfer_start_hour)
    {
        $this->container['external_transfer_start_hour'] = $external_transfer_start_hour;

        return $this;
    }

    /**
     * Gets external_transfer_end_hour
     *
     * @return string
     */
    public function getExternalTransferEndHour()
    {
        return $this->container['external_transfer_end_hour'];
    }

    /**
     * Sets external_transfer_end_hour
     *
     * @param string $external_transfer_end_hour Timestamp da hora final da janela para transferencia externa
     *
     * @return $this
     */
    public function setExternalTransferEndHour($external_transfer_end_hour)
    {
        $this->container['external_transfer_end_hour'] = $external_transfer_end_hour;

        return $this;
    }

    /**
     * Gets is_business_day
     *
     * @return bool
     */
    public function getIsBusinessDay()
    {
        return $this->container['is_business_day'];
    }

    /**
     * Sets is_business_day
     *
     * @param bool $is_business_day Indica se e permitido realizar transferencia externa
     *
     * @return $this
     */
    public function setIsBusinessDay($is_business_day)
    {
        $this->container['is_business_day'] = $is_business_day;

        return $this;
    }

    /**
     * Gets fee_external_transfer
     *
     * @return int
     */
    public function getFeeExternalTransfer()
    {
        return $this->container['fee_external_transfer'];
    }

    /**
     * Sets fee_external_transfer
     *
     * @param int $fee_external_transfer Valor da tarifa para transferencia externa
     *
     * @return $this
     */
    public function setFeeExternalTransfer($fee_external_transfer)
    {
        $this->container['fee_external_transfer'] = $fee_external_transfer;

        return $this;
    }

    /**
     * Gets banks
     *
     * @return \Swagger\Client\Model\KeyValue[]
     */
    public function getBanks()
    {
        return $this->container['banks'];
    }

    /**
     * Sets banks
     *
     * @param \Swagger\Client\Model\KeyValue[] $banks banks
     *
     * @return $this
     */
    public function setBanks($banks)
    {
        $this->container['banks'] = $banks;

        return $this;
    }

    /**
     * Gets account_types
     *
     * @return \Swagger\Client\Model\KeyValue[]
     */
    public function getAccountTypes()
    {
        return $this->container['account_types'];
    }

    /**
     * Sets account_types
     *
     * @param \Swagger\Client\Model\KeyValue[] $account_types account_types
     *
     * @return $this
     */
    public function setAccountTypes($account_types)
    {
        $this->container['account_types'] = $account_types;

        return $this;
    }

    /**
     * Gets limits
     *
     * @return \Swagger\Client\Model\CashinLimits
     */
    public function getLimits()
    {
        return $this->container['limits'];
    }

    /**
     * Sets limits
     *
     * @param \Swagger\Client\Model\CashinLimits $limits limits
     *
     * @return $this
     */
    public function setLimits($limits)
    {
        $this->container['limits'] = $limits;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
