<?php
/**
 * User
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API BaaS - Atar B2B
 *
 * Documentação da API do serviço de Banking as a Service.
 *
 * OpenAPI spec version: v3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.30
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * User Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class User implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'User';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'atar_id' => 'string',
'full_name' => 'string',
'email' => 'string',
'phone' => 'string',
'addresses' => '\Swagger\Client\Model\Address[]',
'gender' => 'string',
'birth_date' => 'string',
'tags' => 'string[]',
'document' => 'string',
'rg_number' => 'string',
'kyc_status' => '\Swagger\Client\Model\KycStatus',
'account_status' => '\Swagger\Client\Model\PaymentAccountStatus',
'has_accepted_residence_declaration' => 'bool',
'has_accepted_terms' => 'bool',
'has_accepted_privacy_policy' => 'bool',
'cbo_id' => 'string',
'cbo_name' => 'string',
'monthly_income' => 'int',
'patrimony' => 'int'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'atar_id' => null,
'full_name' => null,
'email' => null,
'phone' => null,
'addresses' => null,
'gender' => null,
'birth_date' => null,
'tags' => null,
'document' => null,
'rg_number' => null,
'kyc_status' => null,
'account_status' => null,
'has_accepted_residence_declaration' => null,
'has_accepted_terms' => null,
'has_accepted_privacy_policy' => null,
'cbo_id' => null,
'cbo_name' => null,
'monthly_income' => null,
'patrimony' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'atar_id' => 'atarId',
'full_name' => 'fullName',
'email' => 'email',
'phone' => 'phone',
'addresses' => 'addresses',
'gender' => 'gender',
'birth_date' => 'birthDate',
'tags' => 'tags',
'document' => 'document',
'rg_number' => 'rgNumber',
'kyc_status' => 'kycStatus',
'account_status' => 'accountStatus',
'has_accepted_residence_declaration' => 'hasAcceptedResidenceDeclaration',
'has_accepted_terms' => 'hasAcceptedTerms',
'has_accepted_privacy_policy' => 'hasAcceptedPrivacyPolicy',
'cbo_id' => 'cboId',
'cbo_name' => 'cboName',
'monthly_income' => 'monthlyIncome',
'patrimony' => 'patrimony'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'atar_id' => 'setAtarId',
'full_name' => 'setFullName',
'email' => 'setEmail',
'phone' => 'setPhone',
'addresses' => 'setAddresses',
'gender' => 'setGender',
'birth_date' => 'setBirthDate',
'tags' => 'setTags',
'document' => 'setDocument',
'rg_number' => 'setRgNumber',
'kyc_status' => 'setKycStatus',
'account_status' => 'setAccountStatus',
'has_accepted_residence_declaration' => 'setHasAcceptedResidenceDeclaration',
'has_accepted_terms' => 'setHasAcceptedTerms',
'has_accepted_privacy_policy' => 'setHasAcceptedPrivacyPolicy',
'cbo_id' => 'setCboId',
'cbo_name' => 'setCboName',
'monthly_income' => 'setMonthlyIncome',
'patrimony' => 'setPatrimony'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'atar_id' => 'getAtarId',
'full_name' => 'getFullName',
'email' => 'getEmail',
'phone' => 'getPhone',
'addresses' => 'getAddresses',
'gender' => 'getGender',
'birth_date' => 'getBirthDate',
'tags' => 'getTags',
'document' => 'getDocument',
'rg_number' => 'getRgNumber',
'kyc_status' => 'getKycStatus',
'account_status' => 'getAccountStatus',
'has_accepted_residence_declaration' => 'getHasAcceptedResidenceDeclaration',
'has_accepted_terms' => 'getHasAcceptedTerms',
'has_accepted_privacy_policy' => 'getHasAcceptedPrivacyPolicy',
'cbo_id' => 'getCboId',
'cbo_name' => 'getCboName',
'monthly_income' => 'getMonthlyIncome',
'patrimony' => 'getPatrimony'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['atar_id'] = isset($data['atar_id']) ? $data['atar_id'] : null;
        $this->container['full_name'] = isset($data['full_name']) ? $data['full_name'] : null;
        $this->container['email'] = isset($data['email']) ? $data['email'] : null;
        $this->container['phone'] = isset($data['phone']) ? $data['phone'] : null;
        $this->container['addresses'] = isset($data['addresses']) ? $data['addresses'] : null;
        $this->container['gender'] = isset($data['gender']) ? $data['gender'] : null;
        $this->container['birth_date'] = isset($data['birth_date']) ? $data['birth_date'] : null;
        $this->container['tags'] = isset($data['tags']) ? $data['tags'] : null;
        $this->container['document'] = isset($data['document']) ? $data['document'] : null;
        $this->container['rg_number'] = isset($data['rg_number']) ? $data['rg_number'] : null;
        $this->container['kyc_status'] = isset($data['kyc_status']) ? $data['kyc_status'] : null;
        $this->container['account_status'] = isset($data['account_status']) ? $data['account_status'] : null;
        $this->container['has_accepted_residence_declaration'] = isset($data['has_accepted_residence_declaration']) ? $data['has_accepted_residence_declaration'] : null;
        $this->container['has_accepted_terms'] = isset($data['has_accepted_terms']) ? $data['has_accepted_terms'] : null;
        $this->container['has_accepted_privacy_policy'] = isset($data['has_accepted_privacy_policy']) ? $data['has_accepted_privacy_policy'] : null;
        $this->container['cbo_id'] = isset($data['cbo_id']) ? $data['cbo_id'] : null;
        $this->container['cbo_name'] = isset($data['cbo_name']) ? $data['cbo_name'] : null;
        $this->container['monthly_income'] = isset($data['monthly_income']) ? $data['monthly_income'] : null;
        $this->container['patrimony'] = isset($data['patrimony']) ? $data['patrimony'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets atar_id
     *
     * @return string
     */
    public function getAtarId()
    {
        return $this->container['atar_id'];
    }

    /**
     * Sets atar_id
     *
     * @param string $atar_id ATAR ID do usuario
     *
     * @return $this
     */
    public function setAtarId($atar_id)
    {
        $this->container['atar_id'] = $atar_id;

        return $this;
    }

    /**
     * Gets full_name
     *
     * @return string
     */
    public function getFullName()
    {
        return $this->container['full_name'];
    }

    /**
     * Sets full_name
     *
     * @param string $full_name Nome completo do usuario
     *
     * @return $this
     */
    public function setFullName($full_name)
    {
        $this->container['full_name'] = $full_name;

        return $this;
    }

    /**
     * Gets email
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string $email E-mail do usuario
     *
     * @return $this
     */
    public function setEmail($email)
    {
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets phone
     *
     * @return string
     */
    public function getPhone()
    {
        return $this->container['phone'];
    }

    /**
     * Sets phone
     *
     * @param string $phone Telefone do usuario (DDI + DDI + NUMERO)
     *
     * @return $this
     */
    public function setPhone($phone)
    {
        $this->container['phone'] = $phone;

        return $this;
    }

    /**
     * Gets addresses
     *
     * @return \Swagger\Client\Model\Address[]
     */
    public function getAddresses()
    {
        return $this->container['addresses'];
    }

    /**
     * Sets addresses
     *
     * @param \Swagger\Client\Model\Address[] $addresses addresses
     *
     * @return $this
     */
    public function setAddresses($addresses)
    {
        $this->container['addresses'] = $addresses;

        return $this;
    }

    /**
     * Gets gender
     *
     * @return string
     */
    public function getGender()
    {
        return $this->container['gender'];
    }

    /**
     * Sets gender
     *
     * @param string $gender Genero do usuario
     *
     * @return $this
     */
    public function setGender($gender)
    {
        $this->container['gender'] = $gender;

        return $this;
    }

    /**
     * Gets birth_date
     *
     * @return string
     */
    public function getBirthDate()
    {
        return $this->container['birth_date'];
    }

    /**
     * Sets birth_date
     *
     * @param string $birth_date Timestamp da data de nascimento do usuario
     *
     * @return $this
     */
    public function setBirthDate($birth_date)
    {
        $this->container['birth_date'] = $birth_date;

        return $this;
    }

    /**
     * Gets tags
     *
     * @return string[]
     */
    public function getTags()
    {
        return $this->container['tags'];
    }

    /**
     * Sets tags
     *
     * @param string[] $tags Lista de tags do usuario
     *
     * @return $this
     */
    public function setTags($tags)
    {
        $this->container['tags'] = $tags;

        return $this;
    }

    /**
     * Gets document
     *
     * @return string
     */
    public function getDocument()
    {
        return $this->container['document'];
    }

    /**
     * Sets document
     *
     * @param string $document Numero do documento do usuario
     *
     * @return $this
     */
    public function setDocument($document)
    {
        $this->container['document'] = $document;

        return $this;
    }

    /**
     * Gets rg_number
     *
     * @return string
     */
    public function getRgNumber()
    {
        return $this->container['rg_number'];
    }

    /**
     * Sets rg_number
     *
     * @param string $rg_number Numero do RG do usuario
     *
     * @return $this
     */
    public function setRgNumber($rg_number)
    {
        $this->container['rg_number'] = $rg_number;

        return $this;
    }

    /**
     * Gets kyc_status
     *
     * @return \Swagger\Client\Model\KycStatus
     */
    public function getKycStatus()
    {
        return $this->container['kyc_status'];
    }

    /**
     * Sets kyc_status
     *
     * @param \Swagger\Client\Model\KycStatus $kyc_status kyc_status
     *
     * @return $this
     */
    public function setKycStatus($kyc_status)
    {
        $this->container['kyc_status'] = $kyc_status;

        return $this;
    }

    /**
     * Gets account_status
     *
     * @return \Swagger\Client\Model\PaymentAccountStatus
     */
    public function getAccountStatus()
    {
        return $this->container['account_status'];
    }

    /**
     * Sets account_status
     *
     * @param \Swagger\Client\Model\PaymentAccountStatus $account_status account_status
     *
     * @return $this
     */
    public function setAccountStatus($account_status)
    {
        $this->container['account_status'] = $account_status;

        return $this;
    }

    /**
     * Gets has_accepted_residence_declaration
     *
     * @return bool
     */
    public function getHasAcceptedResidenceDeclaration()
    {
        return $this->container['has_accepted_residence_declaration'];
    }

    /**
     * Sets has_accepted_residence_declaration
     *
     * @param bool $has_accepted_residence_declaration Indica se a pessoa aceitou os termos de servico
     *
     * @return $this
     */
    public function setHasAcceptedResidenceDeclaration($has_accepted_residence_declaration)
    {
        $this->container['has_accepted_residence_declaration'] = $has_accepted_residence_declaration;

        return $this;
    }

    /**
     * Gets has_accepted_terms
     *
     * @return bool
     */
    public function getHasAcceptedTerms()
    {
        return $this->container['has_accepted_terms'];
    }

    /**
     * Sets has_accepted_terms
     *
     * @param bool $has_accepted_terms Indica se a pessoa aceitou os termos de servico
     *
     * @return $this
     */
    public function setHasAcceptedTerms($has_accepted_terms)
    {
        $this->container['has_accepted_terms'] = $has_accepted_terms;

        return $this;
    }

    /**
     * Gets has_accepted_privacy_policy
     *
     * @return bool
     */
    public function getHasAcceptedPrivacyPolicy()
    {
        return $this->container['has_accepted_privacy_policy'];
    }

    /**
     * Sets has_accepted_privacy_policy
     *
     * @param bool $has_accepted_privacy_policy Indica se a pessoa aceitou as politicas de privacidade
     *
     * @return $this
     */
    public function setHasAcceptedPrivacyPolicy($has_accepted_privacy_policy)
    {
        $this->container['has_accepted_privacy_policy'] = $has_accepted_privacy_policy;

        return $this;
    }

    /**
     * Gets cbo_id
     *
     * @return string
     */
    public function getCboId()
    {
        return $this->container['cbo_id'];
    }

    /**
     * Sets cbo_id
     *
     * @param string $cbo_id Numero da Classificacao Brasileira de Ocupacoes (cbo) do usuario
     *
     * @return $this
     */
    public function setCboId($cbo_id)
    {
        $this->container['cbo_id'] = $cbo_id;

        return $this;
    }

    /**
     * Gets cbo_name
     *
     * @return string
     */
    public function getCboName()
    {
        return $this->container['cbo_name'];
    }

    /**
     * Sets cbo_name
     *
     * @param string $cbo_name Nome da Classificacao Brasileira de Ocupacoes (cbo) do usuario
     *
     * @return $this
     */
    public function setCboName($cbo_name)
    {
        $this->container['cbo_name'] = $cbo_name;

        return $this;
    }

    /**
     * Gets monthly_income
     *
     * @return int
     */
    public function getMonthlyIncome()
    {
        return $this->container['monthly_income'];
    }

    /**
     * Sets monthly_income
     *
     * @param int $monthly_income Renda mensal
     *
     * @return $this
     */
    public function setMonthlyIncome($monthly_income)
    {
        $this->container['monthly_income'] = $monthly_income;

        return $this;
    }

    /**
     * Gets patrimony
     *
     * @return int
     */
    public function getPatrimony()
    {
        return $this->container['patrimony'];
    }

    /**
     * Sets patrimony
     *
     * @param int $patrimony Patrimonio
     *
     * @return $this
     */
    public function setPatrimony($patrimony)
    {
        $this->container['patrimony'] = $patrimony;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
