<?php
/**
 * PixEmLoteApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API BaaS - Atar B2B
 *
 * Documentação da API do serviço de Banking as a Service.
 *
 * OpenAPI spec version: v3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.30
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * PixEmLoteApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PixEmLoteApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for pixBatchDelete
     *
     * Exlcui um lote e seus itens.
     *
     */
    public function testPixBatchDelete()
    {
    }

    /**
     * Test case for pixBatchGet
     *
     * retorna os lotes cadastrados.
     *
     */
    public function testPixBatchGet()
    {
    }

    /**
     * Test case for pixBatchGetCursor
     *
     * retorna os lotes cadastrados.
     *
     */
    public function testPixBatchGetCursor()
    {
    }

    /**
     * Test case for pixBatchItemDelete
     *
     * Exclui um item do lote.
     *
     */
    public function testPixBatchItemDelete()
    {
    }

    /**
     * Test case for pixBatchItemGet
     *
     * retorna os itens do lote cadastrados.
     *
     */
    public function testPixBatchItemGet()
    {
    }

    /**
     * Test case for pixBatchItemGetCursor
     *
     * retorna os itens do lote cadastrados.
     *
     */
    public function testPixBatchItemGetCursor()
    {
    }

    /**
     * Test case for pixBatchItemPost
     *
     * Insere itens em um lote.
     *
     */
    public function testPixBatchItemPost()
    {
    }

    /**
     * Test case for pixBatchPost
     *
     * Realiza o cadastro de um lote.
     *
     */
    public function testPixBatchPost()
    {
    }

    /**
     * Test case for pixBatchStartProcessPost
     *
     * Inicia o processamento dos itens do lote.
     *
     */
    public function testPixBatchStartProcessPost()
    {
    }
}
