<?php
/**
 * UsersApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API BaaS - Atar B2B
 *
 * Documentação da API do serviço de Banking as a Service.
 *
 * OpenAPI spec version: v3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.30
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * UsersApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UsersApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for payUsersGet
     *
     * Busca um usuario no sistema pelo identificador.
     *
     */
    public function testPayUsersGet()
    {
    }

    /**
     * Test case for payUsersMeGet
     *
     * Busca informacoes do usuario atualmente logado.
     *
     */
    public function testPayUsersMeGet()
    {
    }

    /**
     * Test case for payUsersMePostRelashionship
     *
     * Insere o usuario como relacionamento.
     *
     */
    public function testPayUsersMePostRelashionship()
    {
    }

    /**
     * Test case for payUsersMePut
     *
     * Atualiza informacoes do usuario atualmente logado.
     *
     */
    public function testPayUsersMePut()
    {
    }

    /**
     * Test case for payUsersMeRelationships
     *
     * Retorna os relacionamentos do usuario ordenados pela ultima iteracao.
     *
     */
    public function testPayUsersMeRelationships()
    {
    }

    /**
     * Test case for payUsersMeSubscriptionGet
     *
     * Retorna as informacoes do contrato ativo do usuario.
     *
     */
    public function testPayUsersMeSubscriptionGet()
    {
    }
}
